version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        depends_on:
            - "db"
        command: >
            bash -c "/var/www/html/vendor/bin/doctrine orm:schema-tool:update --force
            && apache2-foreground"
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5
        platform: linux/amd64
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: memory
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
volumes:
    persistent: